import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../../lib/registry";
import { Main } from "@/components/Main";
import { Aside } from "@/components/Aside";
import { Card } from "@/components/Card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Main>
            <Aside />
            <Card>
              {children}
            </Card>
          </Main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
